theme = "lynx"
title = "Atletiekunie.TV"
languageCode = "nl-nl"
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Atletiekunie.tv"
  image = "logo-au.jpg"
  links = [
        {youtube = { href = "https://www.youtube.com/watch?v=REC0ePOttDI", text = "Gouden Spike 2023"} },
        {youtube = { href = "https://www.youtube.com/watch?v=bjKgVBzb3nE", text = "Klaverblad International High Jump Meeting"} },
        {youtube = { href = "https://www.youtube.com/@AtletiekunieTV/streams", text = "AtletiekunieTV Archief"} },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
