baseURL = "/"
title = "Atletiekunie.tv"
languageCode = "nl-nl"
theme = "linkshrubbery"
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Year, Atletiekunie.tv"
disableKinds = ["taxonomy", "term"]

# Configuration Features
[params]
  description = "Your meta description"  # Your meta description of the site
  avatar = "/images/logo-au.jpg"          # Path to avatar image starting from the static directory
  logo = "/images/logo-au.jpg"              # Path to logo image starting from the static directory
  [params.style]                         # CSS style overrides
    backgroundColor = "#f8f9fa"
    fontColor = "#212529"
