theme = "lynx"
title = "Atletiekunie.TV"
languageCode = "nl-nl"
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Atletiekunie.tv"
  image = "logo-au.jpg"
  links = [
        {youtube = { href = "https://www.youtube.com/watch?v=JyKSN30uEBQ", text = "ASICS NK Atletiek 2023 - 28 juli"} },
        {youtube = { href = "https://www.youtube.com/watch?v=OvBj3yNGM2U", text = "ASICS NK Atletiek 2023 - 29 juli"} },
        {youtube = { href = "https://www.youtube.com/watch?v=tPMty43FoWs", text = "ASICS NK Atletiek 2023 - 30 juli"} },
        {youtube = { href = "https://www.youtube.com/@AtletiekunieTV/streams", text = "AtletiekunieTV Archief"} },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
